#!/usr/bin/env ruby

lib = File.expand_path(File.dirname(__FILE__) + "/../lib")
$LOAD_PATH.unshift(lib) if File.directory?(lib) && !$LOAD_PATH.include?(lib)

require "wikidata"
require "wikidata/command_line"

Wikidata::CommandLine.start
